In [19]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt

posts_list = pd.read_pickle('posts_investing.pkl')

df = pd.DataFrame(posts_list)

In [20]:
df.columns

Index(['author', 'author_flair_css_class', 'author_flair_richtext',
       'author_flair_text', 'author_flair_type', 'brand_safe', 'can_mod_post',
       'contest_mode', 'created_utc', 'domain', 'full_link', 'gilded', 'id',
       'is_crosspostable', 'is_reddit_media_domain', 'is_self', 'is_video',
       'link_flair_richtext', 'link_flair_text_color', 'link_flair_type',
       'locked', 'no_follow', 'num_comments', 'num_crossposts', 'over_18',
       'parent_whitelist_status', 'permalink', 'pinned', 'retrieved_on',
       'rte_mode', 'score', 'selftext', 'send_replies', 'spoiler', 'stickied',
       'subreddit', 'subreddit_id', 'subreddit_subscribers', 'subreddit_type',
       'thumbnail', 'title', 'url', 'whitelist_status',
       'link_flair_background_color', 'link_flair_css_class',
       'link_flair_template_id', 'link_flair_text', 'post_hint', 'preview',
       'suggested_sort', 'author_flair_background_color',
       'author_flair_text_color', 'edited', 'banned_by', 'author_cakeday'],
      dtype='object')

In [21]:
df.head()

,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,brand_safe,can_mod_post,contest_mode,created_utc,domain,...,link_flair_template_id,link_flair_text,post_hint,preview,suggested_sort,author_flair_background_color,author_flair_text_color,edited,banned_by,author_cakeday
0,Kutukuprek,None,[],None,text,True,False,False,1522540627,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,pugcastle,None,[],None,text,True,False,False,1522540098,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,hansuswurstus00,None,[],None,text,True,False,False,1522539335,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AxDal,None,[],None,text,True,False,False,1522536152,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,henjsmii,None,[],None,text,True,False,False,1522534256,self.investing,...,5a55ab96-9665-11e3-b5c1-12313d224170,Help,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df

,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,brand_safe,can_mod_post,contest_mode,created_utc,domain,...,link_flair_template_id,link_flair_text,post_hint,preview,suggested_sort,author_flair_background_color,author_flair_text_color,edited,banned_by,author_cakeday
0,Kutukuprek,None,[],None,text,True,False,False,1522540627,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,pugcastle,None,[],None,text,True,False,False,1522540098,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,hansuswurstus00,None,[],None,text,True,False,False,1522539335,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AxDal,None,[],None,text,True,False,False,1522536152,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,henjsmii,None,[],None,text,True,False,False,1522534256,self.investing,...,5a55ab96-9665-11e3-b5c1-12313d224170,Help,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,RickC137-wubba,None,[],None,text,True,False,False,1518814207,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2996,Eddie_Quesadilla,None,[],None,text,True,False,False,1518814147,self.investing,...,52f27b18-9665-11e3-b9b7-22000aa47206,Discussion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2997,Robot_Sniper,None,[],None,text,True,False,False,1518814033,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2998,Baloo2009,None,[],None,text,True,False,False,1518813811,self.investing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,notwiththatattidude,None,[],None,text,True,False,False,1518813628,self.investing,...,NaN,NaN,self,"{'enabled': False, 'images': [{'id': 'A-tD_-sc...",NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt

posts_list = pd.read_pickle('comments_investing.pkl')

df = pd.DataFrame(posts_list)

In [24]:
df.columns

Index(['author', 'author_created_utc', 'author_flair_css_class',
       'author_flair_template_id', 'author_flair_text', 'author_fullname',
       'body', 'can_gild', 'controversiality', 'created_utc', 'distinguished',
       'gilded', 'id', 'is_submitter', 'link_id', 'nest_level', 'no_follow',
       'parent_id', 'permalink', 'reply_delay', 'retrieved_on', 'score',
       'send_replies', 'stickied', 'subreddit', 'subreddit_id',
       'subreddit_type', 'user_removed', 'edited', 'author_cakeday',
       'mod_removed'],
      dtype='object')

In [25]:
df

,author,author_created_utc,author_flair_css_class,author_flair_template_id,author_flair_text,author_fullname,body,can_gild,controversiality,created_utc,...,score,send_replies,stickied,subreddit,subreddit_id,subreddit_type,user_removed,edited,author_cakeday,mod_removed
0,beigebaron,1.349320e+09,None,None,None,t2_97c6y,"Bitcoin &lt; 1000, in my opinion it's a near c...",True,0,1522540753,...,-1,True,False,investing,t5_2qhhq,public,NaN,NaN,NaN,NaN
1,slackerdx02,1.496616e+09,None,None,None,t2_2lu67v8,All of your replies are the bear case for the ...,True,0,1522540703,...,3,True,False,investing,t5_2qhhq,public,NaN,NaN,NaN,NaN
2,Optimisticz,1.501644e+09,None,None,None,t2_90g668o,Commenting as I am interested in doing an MBA ...,True,0,1522540624,...,4,True,False,investing,t5_2qhhq,public,NaN,NaN,NaN,NaN
3,posam,1.351260e+09,None,None,None,t2_9f29p,Sure it isn't bad but that's throwing money in...,True,1,1522540368,...,3,True,False,investing,t5_2qhhq,public,NaN,NaN,NaN,NaN
4,TheHolyLampshade,1.299044e+09,None,None,None,t2_4wram,Those are just securities they trade. All are ...,True,0,1522540284,...,2,True,False,investing,t5_2qhhq,public,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,cfbnerd,NaN,None,None,None,NaN,I can't give you proof. It's your word against...,True,0,1522260085,...,15,True,False,investing,t5_2qhhq,public,NaN,1.522260e+09,NaN,NaN
4996,manofthewild07,1.350142e+09,None,None,None,t2_9ahfz,I invest with Fidelity.\n\nI got into IEFA (Eu...,True,0,1522260083,...,3,True,False,investing,t5_2qhhq,public,NaN,NaN,NaN,NaN
4997,return_of_the_ring,1.459892e+09,None,None,None,t2_wwlqr,"Jeff Bezos owns Washington Post, not Amazon. T...",True,0,1522260069,...,9,True,False,investing,t5_2qhhq,public,NaN,NaN,NaN,NaN
4998,jsf67,1.379587e+09,None,None,None,t2_d7ojb,I'm pretty sure there are way more jobs than p...,True,0,1522260046,...,6,True,False,investing,t5_2qhhq,public,NaN,NaN,NaN,NaN
4999,donkeyotee,1.320631e+09,None,None,None,t2_670gk,"Ted Cruz, among others, was just posting a few...",True,0,1522260007,...,2,True,False,investing,t5_2qhhq,public,NaN,NaN,NaN,NaN

In [26]:
df['body']

0       Bitcoin &lt; 1000, in my opinion it's a near c...
1       All of your replies are the bear case for the ...
2       Commenting as I am interested in doing an MBA ...
3       Sure it isn't bad but that's throwing money in...
4       Those are just securities they trade. All are ...
                              ...
4995    I can't give you proof. It's your word against...
4996    I invest with Fidelity.\n\nI got into IEFA (Eu...
4997    Jeff Bezos owns Washington Post, not Amazon. T...
4998    I'm pretty sure there are way more jobs than p...
4999    Ted Cruz, among others, was just posting a few...
Name: body, Length: 5000, dtype: object

In [27]:
count = 0
for x in df['body']:
    if 'china' in str(x).lower():
        count+=1
print(count)

30

In [28]:
count = 0
for x in df['body']:
    if 'crash' in str(x).lower():
        count+=1
print(count)

85

In [29]:
count = 0
for x in df['body']:
    if 'sell' in str(x).lower():
        count+=1
print(count)

225

In [30]:
count = 0
for x in df['body']:
    if 'puts' in str(x).lower():
        count+=1
print(count)

28

In [31]:
count = 0
for x in df['body']:
    if 'calls' in str(x).lower():
        count+=1
print(count)

30

In [32]:
s = ""
import nltk

In [33]:
for x in df['body']:
    s+=str(x) + '. '

In [43]:
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
additional_stopwords = """one get like r would think going"""
stop_words += additional_stopwords.split()
tokenizer = RegexpTokenizer(r'\w+')
filtered = tokenizer.tokenize(s)
new_filtered = []
for x in filtered:
    if str(x).lower() not in stop_words:
        new_filtered += [x]

In [44]:
from collections import Counter
counts = Counter(new_filtered)
counts.most_common(100)

[('Amazon', 575),
 ('market', 513),
 ('people', 500),
 ('money', 445),
 ('time', 407),
 ('Tesla', 388),
 ('gt', 361),
 ('much', 351),
 ('deleted', 347),
 ('company', 344),
 ('com', 343),
 ('buy', 337),
 ('https', 319),
 ('stock', 317),
 ('really', 316),
 ('years', 306),
 ('good', 303),
 ('even', 298),
 ('make', 293),
 ('go', 287),
 ('could', 285),
 ('price', 272),
 ('business', 267),
 ('companies', 263),
 ('know', 260),
 ('still', 246),
 ('1', 243),
 ('long', 243),
 ('year', 243),
 ('way', 238),
 ('lot', 235),
 ('Walmart', 234),
 ('see', 232),
 ('want', 227),
 ('car', 225),
 ('something', 224),
 ('use', 220),
 ('right', 215),
 ('www', 214),
 ('also', 214),
 ('point', 212),
 ('stocks', 209),
 ('2', 207),
 ('tax', 202),
 ('5', 201),
 ('say', 200),
 ('need', 197),
 ('investing', 193),
 ('3', 192),
 ('sure', 191),
 ('many', 184),
 ('amp', 183),
 ('back', 182),
 ('probably', 181),
 ('10', 178),
 ('take', 173),
 ('term', 171),
 ('cash', 169),
 ('said', 168),
 ('well', 165),
 ('actually', 162),
 ('pay', 161),
 ('better', 159),
 ('things', 158),
 ('Trump', 158),
 ('US', 155),
 ('sell', 152),
 ('already', 151),
 ('new', 151),
 ('growth', 149),
 ('value', 148),
 ('investment', 147),
 ('thing', 147),
 ('fund', 146),
 ('look', 145),
 ('every', 144),
 ('risk', 143),
 ('though', 142),
 ('invest', 141),
 ('low', 140),
 ('day', 140),
 ('short', 139),
 ('may', 139),
 ('high', 137),
 ('work', 137),
 ('bad', 136),
 ('less', 135),
 ('around', 134),
 ('last', 132),
 ('put', 132),
 ('great', 131),
 ('cars', 131),
 ('pretty', 130),
 ('100', 130),
 ('never', 129),
 ('since', 129),
 ('small', 129),
 ('looking', 126),
 ('future', 125),
 ('driving', 125)]

In [36]:
count = 0
for x in df['body']:
    if 'china' in str(x).lower():
        count+=1
print(count)

30